version: '2.15'

services:
 postgres:
    image: postgres:15.2
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=urbalance
      - POSTGRES_USER=josafat
      - POSTGRES_PASSWORD=balances_508!$
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
